export const GET_DATA_GENERATION_EVENTS_HISTORY_REQUEST = 'GET_DATA_GENERATION_EVENTS_HISTORY_REQUEST';
export const GET_DATA_GENERATION_EVENTS_HISTORY_SUCCESS = 'GET_DATA_GENERATION_EVENTS_HISTORY_SUCCESS';
export const GET_DATA_GENERATION_EVENTS_HISTORY_FAILURE = 'GET_DATA_GENERATION_EVENTS_HISTORY_FAILURE';

export const GENERATE_DATA_REQUEST = 'GENERATE_DATA_REQUEST';
export const GENERATE_DATA_SUCCESS = 'GENERATE_DATA_SUCCESS';
export const GENERATE_DATA_FAILURE = 'GENERATE_DATA_FAILURE';

export const RESET_GENERATED_DATA = 'RESET_GENERATED_DATA';
